In [27]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [28]:
#loading data
df = pd.read_csv('IRIS.csv')
df.head()


sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [35]:
#Label Encoding
le=LabelEncoder()
df['species']=le.fit_transform(df['species'])
print(df)
y = to_categorical(df['species'])

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]


In [36]:
#Features
X=df.drop(columns=['species'],axis=1)
y=df['species']
print(X)
print(y)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64


In [47]:
#train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]
     sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5    

In [50]:
#model creation
#forward propogation : Input layer , Hidden Layer and Output Layer
model=Sequential()
model.add(Dense(128,activation='relu',input_dim=4))
model.add(Dense(64,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.summary()


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 128)            │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,091 (35.51 KB)

 Trainable params: 9,091 (35.51 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
#Backward Propogation: Loss function
model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam')
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5628  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5180 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4539 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4195 
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4421 
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4149 
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3838 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3768 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3378 
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3330 


In [56]:
#predicted yy
y_pred=model.predict(X_test)
print(y_pred)
y_pred=np.argmax(y_pred,axis=1)
print(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[[1.5746133e-02 5.3561747e-01 4.4863647e-01]
 [9.7242010e-01 2.4892211e-02 2.6877210e-03]
 [2.4172202e-04 1.7740151e-01 8.2235676e-01]
 [1.5769502e-02 5.0331908e-01 4.8091146e-01]
 [1.3986432e-02 6.0140425e-01 3.8460928e-01]
 [9.6245205e-01 3.3344541e-02 4.2033219e-03]
 [7.5084105e-02 6.2676054e-01 2.9815537e-01]
 [3.9989026e-03 3.7604252e-01 6.1995852e-01]
 [9.3698623e-03 4.9848658e-01 4.9214357e-01]
 [4.4063326e-02 6.3383609e-01 3.2210049e-01]
 [5.2649747e-03 3.7241659e-01 6.2231845e-01]
 [9.5282227e-01 4.1147429e-02 6.0303919e-03]
 [9.8017764e-01 1.7860839e-02 1.9615071e-03]
 [9.5174789e-01 4.2256154e-02 5.9960359e-03]
 [9.7330928e-01 2.3598852e-02 3.0918755e-03]
 [1.6419809e-02 5.1765001e-01 4.6593019e-01]
 [1.0311118e-03 1.9942620e-01 7.9954267e-01]
 [3.7330404e-02 6.1355239e-01 3.4911719e-01]
 [1.6172426e-02 4.8344290e-01 5.0038469e-01]
 [1.1598200e-03 2.0941912e-01 7.8942102e-01]
 [9.3596762e-01 5.5329155e-02 8.7033175e-03]
 [6.4994195e-03 3

In [58]:
#confusion_matrix and classification_Report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
fig , ax = plt.subplots(figsize=(5,5))
sb.heatmap(cm,annot=True,linewidth=0.5,linecolor='red',fmt='.0f',ax=ax)
plt.xlabel('')